# dependabot.yaml reference: https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
#
# Notes:
# - Status and logs from dependabot are provided at
#   https://github.com/jupyterhub/action-major-minor-tag-calculator/network/updates.
# - YAML anchors are not supported here or in GitHub Workflows.
# - We explicitly set the "maintenance" label on dependencies influencing the
#   action to help our changelog generator tool github-activity to categorize
#   PRs.
#
version: 2
updates:
  # npm dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
      time: "05:00"
      timezone: Etc/UTC
    allow:
      - dependency-type: production
      - dependency-type: development
    groups:
      all-dependencies:
        patterns: ["*"]
    labels:
      - maintenance
      - dependencies

  # Maintain dependencies in our GitHub Workflows
  - package-ecosystem: github-actions
    directory: /
    labels: [ci]
    schedule:
      interval: monthly
      time: "05:00"
      timezone: Etc/UTC
