# dependabot.yml reference: https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates
#
# Notes:
# - Status and logs from dependabot are provided at
#   https://github.com/jupyterhub/action-major-minor-tag-calculator/network/updates.
# - YAML anchors are not supported here or in GitHub Workflows.
# - We explicitly set the "maintenance" label on dependencies influencing the
#   action to help our changelog generator tool github-activity to categorize
#   PRs.
#
version: 2
updates:
  # npm production dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: weekly
    labels:
      - maintenance
      - dependencies
    allow:
      # To avoid PR noise, we only automate version bumps to the package.json's
      # "dependencies", and ignore those in "devDependencies" on a weekly basis.
      - dependency-type: production

  # npm development dependencies
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    labels:
      - dependencies
    allow:
      # To avoid PR noise, we automate version bumps to the package.json's
      # "devDepenencies" on a monthly basis.
      - dependency-type: production

  # Maintain dependencies in our GitHub Workflows
  - package-ecosystem: github-actions
    directory: /
    labels: [ci]
    schedule:
      interval: monthly
      time: "05:00"
      timezone: Etc/UTC
