# Reference: https://docs.github.com/en/actions/creating-actions/metadata-syntax-for-github-actions
---
author: Simon Li
name: major-minor-tag-calculator
description: Calculate major and minor semver tags, e.g. for tagging containers

# Manually keep the input-, and output- descriptions in sync with the readme!
inputs:
  githubToken:
    required: false
    description: |-
      The GitHub token, required so this action can fetch tags using the GitHub API. If this parameter is not set then `defaultTag` (if set) or an empty list will be returned.
    default: ""
  prefix:
    required: false
    description: |-
      One or more whitespace or comma deliminated prefixes for returned tags.

      All permutations of prefixes and suffixes are considered.
    default: ""
  suffix:
    required: false
    description: |-
      One or more whitespace or comma deliminated suffixes for returned tags.

      All permutations of prefixes and suffixes are considered.
    default: ""
  defaultTag:
    required: false
    description: |-
      If the tag output would be empty return this tag instead.
      This can be useful for running a workflow in pull requests where no suitable git references are present.
      `prefix` or `suffix` are _not_ automatically added.
    default: ""
  branchRegex:
    required: false
    description: |-
      If a branch name does not match this regex return `defaultTag` or empty instead.
    default: "^[a-zA-Z0-9_][a-zA-Z0-9._-]{0,127}$"
outputs:
  tags:
    description: A JSON formatted list of calculated tags.

runs:
  using: node20
  main: dist/index.js

branding:
  icon: bookmark
  color: purple
