name: build-test
on:
  pull_request:
  push:
    branches:
      - main
    # All other branches are handled in test-and-update which auto-formats,
    # updates dist, runs tests, and pushes the changes back to the branch
    tags:
      - "*"

jobs:
  build: # make sure build/ci work properly, and that dist was updated
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.1.0
      - run: npm install
      - run: npm run lint
      - run: npm run all
      - run: |
          git diff --exit-code
          if [ -n "$(git status --porcelain)" ]; then
            exit 1
          fi
